AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

# Rubocop is too stupid too see that the variable is used
Lint/UselessAssignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 50

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 25

Metrics/MethodLength:
  Max: 100

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableName:
  EnforcedStyle: snake_case

Security/JSONLoad:
  Enabled: false

Style/CaseLikeIf:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/PerlBackrefs:
  AutoCorrect: false

# Allow explicit return
Style/RedundantReturn:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets
