AllCops:
  TargetRubyVersion: 2.4

Style/PerlBackrefs:
  AutoCorrect: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

# Allow explicit return
Style/RedundantReturn:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 100

Metrics/LineLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Enabled: false

Naming/VariableName:
  EnforcedStyle: snake_case
